spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/service_db?useSSL=false&autoreconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

## myBaties配置

mybatis:
   typeAliasesPackage: com.wangpu.model
      mapperLocations: classpath: com/wangpu/dao/*.xml
